export const SET_FIELD_VALUE = 'SET_FIELD_VALUE';
export const SET_ERROR_MSG = 'SET_ERROR_MSG';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const TOGGLE_LOADING_INDICATOR = 'TOGGLE_LOADING_INDICATOR';
